### PR TITLE
Update BulkUploadTask

### PR DESCRIPTION
**Pull request by lukaslentner**
Added the possibility to add an acl to the object putted

### CODE REVIEW

**Comment by lukaslentner** [comment]
Hi,
I am not sure what is the problem here. Can you please help?!
I tried to format the file I updated correctly but it still fails....

Thankx
Lukas

**Comment by lukaslentner** [comment]
I did it on a Windows machine, can it be that gradle suddenly used windows line endings and so on?

**Comment by dai0304** [comment]
please fix CI build

**Comment by wreulicke** [comment]
@lukaslentner 

Could you try followings ? 

```bash
$ ./gradlew spotlessApply
```

**Pull request closed without merging**
