### PR TITLE
#52 Support CloudFormation stack tags

### PR DESCRIPTION
**Pull request by atschabu**
Followed the way Parameters get configured and passed in. Also added usage to sample code.

### CODE REVIEW

**Comment by atschabu** [comment]
Just realized I named my local branch incorrectly :D ... hope that isn't an issue

**Comment by atschabu** [comment]
Check fails at a class, that I haven't manipulated :(

**Comment by dai0304** [comment]
Sorry, CircleCI checking is now experimental.
It will be fixed later.

**Comment by ashlineldridge** [comment]
Was going to submit a PR for this. This change would be much appreciated 👍

**Comment by atschabu** [comment]
Do you still need something from me, or is this good enough to be accepted?

**Pull request merged**
