### PR TITLE
Log stack events if in info mode

### PR DESCRIPTION
**Pull request by donalhenry**
Created branch latest state of develop branch in classmethod

### CODE REVIEW

**Comment by donalhenry** [comment]
@dai0304 Do you plan to target this pull for 0.36?

**Comment by dai0304** [comment]
It is not good that no output is printed in log for a long time.
When this change is applied and if the last event is IN_PROGRESS status for a long time, nothing is output to logger.  This makes some users worry...

Would you do some output whenever new events was not found?

**Comment by donalhenry** [comment]
What I could do is output  a 'status' line if we pass through the while loop and there are no new events lines to output.  That would provide consistent feedback during a long stack update.

**Comment by donalhenry** [comment]
I just reread your comment.  I will do exactly what you suggested and create another pull request.

**Pull request closed without merging**
