### PR TITLE
Lambda Publish Version, Create Alias and Update Alias tasks

### LINKED ISSUE #127: Support for aliases and versions in Upload Lambda task

### PR DESCRIPTION
**Pull request by frankfarrell**
Closes #127 and #128 

These 3 tasks correspond to the following cli commands: 
1) https://docs.aws.amazon.com/cli/latest/reference/lambda/publish-version.html
2) https://docs.aws.amazon.com/cli/latest/reference/lambda/create-alias.html
3) https://docs.aws.amazon.com/cli/latest/reference/lambda/update-alias.html

The main use of these tasks is that you can publish new versions of lambda functions, and assign them to lambda aliases. Routing config is also configured such that you can route a percentage of traffic to another version. 2 extra variables are included useNextVersion and usePreviousVersion to avoid having to write it manually. 
http://docs.aws.amazon.com/lambda/latest/dg/lambda-traffic-shifting-using-aliases.html

Although it is already possible to publish in the MigrateFunction this could be useful to promote a function that is already migrated to a version. Eg Keep pointing $LATEST to dev alias and when you are satisfied, PublishVersion + UpdateAlias for prod.

### CODE REVIEW

**Comment by dai0304** [comment]
Could you update README?

**Comment by frankfarrell** [comment]
Will do, README is updated now

**Comment by frankfarrell** [comment]
@dai0304 When are you planning to release version 0.38? 
Thanks

**Comment by dai0304** [comment]
I’ll release in this weekend!

**Comment by dai0304** [comment]
https://plugins.gradle.org/plugin/jp.classmethod.aws
0.38 is out

**Pull request merged**
