### PR TITLE
#64 -- runtime can be updated on an existing lambda

### PR DESCRIPTION
**Pull request by gcmcnutt**
This fix primarily allows for runtime to be updated.

Secondary support is it inherits settings from an existing lambda, simplifying the gradle script to only need to list changes.

### CODE REVIEW

**Comment by dai0304** [comment]
> Format violations were found. Run 'gradlew spotlessApply' to fix them.

Fix code format.

```
$ ./gradlew spotlessApply
$ git commit
$ git push
```

**Comment by dai0304** [comment]
please rebase onto develop HEAD.

**Comment by dai0304** [comment]
CI should pass.
https://circleci.com/gh/classmethod/gradle-aws-plugin/27#artifacts/containers/0

**Comment by gcmcnutt** [comment]
I'm on it...

**Comment by blundell** [comment]
would have been nice to see an example usage in the PR description..

**Pull request merged**
